//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduling
{
    using System;
    using System.Collections.Generic;
    
    public partial class Time
    {
        public System.Guid Guid { get; set; }
        public string Name { get; set; }
        public int Minutes { get; set; }
        public string PeriodOfDay { get; set; }
    }
}
